### ISSUE TITLE
Offline issues

### ISSUE THREAD

**Issue by hirro** [logentries/le_android#17]
I am having some problems with that the logging gets stuck after I go offline for some time (and then back on ofc).

Is there any known work-around for this? Otherwise I can look into it.

**Comment by StephenHynes7** [comment]
Hey @hirro, what sort of behaviour do you see? Are you seeing logs being dropped? What I think is happening for you you is that when you go offline we start filling up the in memory queue, when this queue is full we actually still add to it but remove the last item in the queue. That could explain any beahviour which would see your logs dropped or out of order.

**Comment by hirro** [comment]
Hi there! I have sent a PR with some comments. I tested it successfully on my device.
