### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by hirro** [logentries/le_android#19]
Which license is this the Android logger project under?

**Comment by StephenHynes7** [comment]
While one is not specified I would imagine that if we were to add one in it would be the MIT license.

**Comment by hirro** [comment]
It would be really good if everything was explicitly licensed as MIT so
that there are no doubts about the usability of this library in commercial
products.

2015-04-07 12:05 GMT+02:00 Stephen Hynes <notifications@github.com>:

**Comment by snodnipper** [comment]
Agreed - we need a license for this code.  Many organisations would not include this code without explicit licensing.

**Comment by vilda** [comment]
I'll add license in a sec...

**Comment by vilda** [comment]
Done! Thanks @hirro @snodnipper
