### ISSUE TITLE
logentries should not lose logs when the application is killed or closed

### ISSUE THREAD

**Issue by Jayroo5245** [logentries/le_android#22]
Currently, (per Mike Neville-O'Neill) if the Android application is killed or closed then those logs will be lost and not uploaded.

I would expect the logs to be persisted (to file or db) and then uploaded later. Very similar to how most Analytic sdk's work like Google Analytics or https://get.fabric.io/.

More info: https://support.logentries.com/hc/en-us/requests/7034?flash_digest=02223b66318b390310ccd0e2724e1fa3396866be&flash_digest=aaccccb1c59ed1d4feebc47d90ccd5d189bee951

**Comment by StephenHynes7** [comment]
The new library will write locally versus storing logs in memory when connection has been lost, should mean we are more fault tolerant, check #27 and give some feedback :)

**Comment by StephenHynes7** [comment]
@Jayroo5245 I have merged in. Would appreciate if you check out the latest jar https://github.com/logentries/le_android/blob/master/lib/logentries-android.jar and give us your thoughts.

**Comment by Jayroo5245** [comment]
Thanks @StephenHynes7 . I am at a conference today but i will take a look next week. Thanks so much!

**Comment by Jayroo5245** [comment]
@StephenHynes7 another question, do you guys compress your payloads and/or batch upload the logs?

**Comment by Jayroo5245** [comment]
Have you uploaded your new build to mavenCentral yet? I am using "compile files('libs/logentries-android-2.1.4.jar')" in build.gradle.

**Comment by ConallH** [comment]
@Jayroo5245 the logs will be uploaded in batch upon reconnection. Not yet, but we are currently in the process of adding it so hopefully it will be up soon!

**Comment by Jayroo5245** [comment]
Thanks @ConallH let me know when its available on mavenCentral and i will play with it.

Thanks

**Comment by Jayroo5245** [comment]
@ConallH is this new sdk ready to be pulled from maven?

**Comment by Jayroo5245** [comment]
Actually, sorry, I thought you had a mvn repo for this... Is there an official version of the jar I should use?

**Comment by Jayroo5245** [comment]
The one linked above doesn't have a version name: IE logentries-android-2.1.4.jar

**Comment by StephenHynes7** [comment]
Ill double check when I can about the jar linked in github.

Maven central is taking longer then expected which is a bit of a pain but
it's on top of Conalls todo list ;)

**Comment by Jayroo5245** [comment]
Hi @StephenHynes7 did you get a chance to add the jar in maven or give me a jar that has a version attached to it? Thanks
