### ISSUE TITLE
logentries should handle connectivity changes automatically

### ISSUE THREAD

**Issue by Jayroo5245** [logentries/le_android#23]
Currently, (per Mike Neville-O'Neill) if the Android application does not have connectivity then the logs will not be uploaded unless "uploadAllLogs()" is called manually.

I would expect logentries sdk to either handle this by default or have a setting to do it. This is very similar to how most Analytic tools work like Google Analytics or https://get.fabric.io/. I add a log or a data point and the sdk just handles it.

More info: https://support.logentries.com/hc/en-us/requests/7034?flash_digest=02223b66318b390310ccd0e2724e1fa3396866be&flash_digest=aaccccb1c59ed1d4feebc47d90ccd5d189bee951

**Comment by lochetti** [comment]
Same problem here. It would be very helpful if the SKD could handle connectivity changes. Using ga instead, for now.

**Comment by Jayroo5245** [comment]
+1

**Comment by luksfarris** [comment]
This would be awesome

**Comment by StephenHynes7** [comment]
This should be fixed in the upcoming PR

**Comment by Jayroo5245** [comment]
That's awesome! Thanks @StephenHynes7 ! Will you post the new artifact when its released?

**Comment by Jayroo5245** [comment]
Any status update on https://github.com/logentries/le_android/issues/22 @StephenHynes7 ?

**Comment by StephenHynes7** [comment]
@Jayroo5245 I will indeed. Feel free to check out the length #27 PR

**Comment by Jayroo5245** [comment]
Thanks =)
