### ISSUE TITLE
java.lang.IllegalThreadStateException: Thread already started

### ISSUE THREAD

**Issue by olivierlemee** [logentries/le_android#32]
Hello,
I try to use the new version of the lib since Android app but during .log(...) method call, I have always an exception java.lang.IllegalThreadStateException: Thread already started

In the stack I see this exception (but I don't want a file appender is used, I want that remote platform is used) >

12-04 08:38:50.226: E/LogentriesAndroidLogger(6451): Cannot load logs from the local storage: /data/data/com.fitmove.application.player/files/LogentriesLogStorage.log: open failed: ENOENT (No such file or directory)

I try to add log4j.xml file like for java use, but without change (with or without the log4j.xml file, the exception is throwed).

Thanks for your quick help about this library and problem.

Regards

**Comment by olivierlemee** [comment]
Hi, I found the problem. An exception is throws when the Android app create several threads (eg IntentService instances which are executed in parallel) and create a new instance of the AndroidLogger.
In this case, an exception is throwed because 2 parallel instances of the logger try to execute a .log(...) method and the current AndroidLogger class don't support (I suppose) the parallel access to appender or other features.

To avoid this behavior, I implement a singleton of the AndroidLogger instance that I use from all the IntentService components. Like this, the exception is not thrown.

Perhaps it could be interested to enhance the documentation about the usage of the AndroidLogger for add mandatory use of singleton if multiple use in Intent Services (which can be processed in parallel model by Android).

Regards

**Comment by mateusgrb** [comment]
Here's the only place where I could find a proper explanation for this issue. Should definitely be in the docs.
